title: Logitech Media Server Downloads
description: >- # this means to ignore newlines until "baseurl:"
  Download Logitech Media Server to feed music to your Squeezebox, Squeezelite
  based players or SqueezePlay and compatible software packages.
  Free the Music!
github_username:  LMS-Community

# Build settings
data_dir: .
lsi: false
safe: true
source: .
incremental: false