title: Lyrion Music Server Downloads
description: >- # this means to ignore newlines until "baseurl:"
  Download Lyrion Music Server to feed music to your Squeezebox, Squeezelite
  based players or SqueezePlay and compatible software packages.
  Free the Music!
github_username:  LMS-Community

# Build settings
data_dir: .
lsi: false
safe: true
source: .
incremental: false

exclude:
  - test.mjs
  - package*
  - tools
  - node_modules
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/